# Generated by Django 2.0.1 on 2018-01-25 16:56
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('end_date', models.DateTimeField(verbose_name='date finished')),
                ('autor', models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votaciones.Consulta')),
            ],
        ),
    ]
