# Generated by Django 2.0.1 on 2018-02-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0002_invitacion_voto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='end_date',
            field=models.DateTimeField(verbose_name='date end'),
        ),
    ]
