# Generated by Django 2.0.1 on 2018-02-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0003_auto_20180201_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='autor',
        ),
    ]
